---
title: "index"
author: "Julia Parish"
date: "11/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Welcome

```{r, message=FALSE}
# get libraries
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  bbest/clockify,
  dplyr, DT, ggplot2,
  quiet = TRUE)

```

```{r, message=FALSE}
api_txt <- "/Users/julia/Documents/private/clockify_api-key.txt"
project_name <- "jaws|bren"

```

```{r}
# use API key to authenticate
CLOCKIFY_API_KEY <- readLines(api_txt)
set_api_key(CLOCKIFY_API_KEY)

```

```{r, message=FALSE}
# get data
d_times <- time_entries_all()
# table(d_times$project_name) # confirm project_name
d_times <- d_times %>%
  filter(
    project_name == !!project_name) %>%
  select(
    task_name, time_start, duration_hrs,
    user_name, description) %>%
  arrange(task_name, time_start)

```

## JAWS|BREN {.tabset}

### 1. Overall

```{r}
# plot ALL
plot_burndown(
  d_times,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-12-09"), # day after
  hrs = 40)

# table ALL
datatable(d_times)
```

### 2. Define Scope/Purpose/Plan

```{r}
# plot scope|purpose|plan
scope <- "Define Scope/Purpose/Plan"

d_scope <- d_times %>% 
  filter(task_name == !!scope)

plot_burndown(
  d_scope,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-11-04"), # day after
  hrs = 5)

# table scope
datatable(d_scope)
```
### 3. Find Data and Import

```{r}
# plot find data and import
data <- "Find Data and Import"

d_data <- d_times %>% 
  filter(task_name == !!data)

plot_burndown(
  d_data,
  beg = as.Date("2021-11-02"), # day before
  end = as.Date("2021-11-06"), # day after
  hrs = 5)

# table scope
datatable(d_data)

```
### 4. Tidy and Transform

```{r}
# plot Tidy (clean and combine) and transform
tidy <- "Tidy (clean and combine) and Transform"

d_tidy <- d_times %>% 
  filter(task_name == !!tidy)

plot_burndown(
  d_tidy,
  beg = as.Date("2021-11-02"), # day before
  end = as.Date("2021-11-08"), # day after
  hrs = 5)

# table scope
datatable(d_tidy)
```
### 5. Exploratory Visualization

```{r}
# plot Exploratory Visualization (Brainstorming)
viz <- "Exploratory Visualization (Brainstorming)"

d_viz <- d_times %>% 
  filter(task_name == !!viz)

plot_burndown(
  d_viz,
  beg = as.Date("2021-11-07"), # day before
  end = as.Date("2021-11-20"), # day after
  hrs = 5)

# table scope
datatable(d_viz)
```

### 5. Model/Refine

```{r}
# plot Model/Refine
model <- "Model/Refine"

d_model <- d_times %>% 
  filter(task_name == !!model)

plot_burndown(
  d_model,
  beg = as.Date("2021-11-11"), # day before
  end = as.Date("2021-11-30"), # day after
  hrs = 10)

# table scope
datatable(d_model)
```
### 6. Communicate

```{r}
# plot Model/Refine
communicate <- "Communicate"

d_comm <- d_times %>% 
  filter(task_name == !!communicate)

plot_burndown(
  d_comm,
  beg = as.Date("2021-11-14"), # day before
  end = as.Date("2021-12-09"), # day after
  hrs = 10)

# table scope
datatable(d_comm)
```
